### ISSUE TITLE
Enabing VIOMMU inside QEMU?

### ISSUE THREAD

**Issue by alokprasad** [awilliam/qemu-kvm-vfio#1]
Not sure, it is the right place to address this , Does devices inside QEMU needs vIOMMU when binded by VFIO in host.
and to enable vIOMMU inside qemu and quest OS

**Comment by awilliam** [comment]
Please try one of qemu-devel, qemu-discuss, or vfio-users mailing list.  This is a developer branch, not the upstream project.  Issue trackers should be used to file bugs, not for general questions.
